### ISSUE TITLE
Autocomplete

### ISSUE THREAD

**Issue by NinjaGrandpa** [NinjaGrandpa/valheim-recipe-bot#10]
# Autocomplete

Bygg funktionalitet för /recipe så att receptet du söker efter fylls i automatiskt.

### To-do:
- [x] recipe.ts
   - [x]  .setAutocomplete
   - [x] autocomplete handler
- [x] onInteraction.ts
   - [x] Kolla om en interaction är inputcommand
   - [x] Kolla om interaction är autocomplete
   - [x] Kalla på autocomplete om interaktionen innehåller ett command
